#!/bin/bash
# Make Helios/ARM on Linux

export HPROC=ARM
export HHOST=LINUX_AMD64

export HSRC=/giga/HeliosRoot/Helios-NG

export HPROD=/giga/HeliosRoot/Production/ARM

export HHOSTBIN=/giga/bin_linux

export HLICENSEE=PERIHELION_ARM

export NCFLAGS=-D__CROSSCOMP

export C_LIBDIR=$HPROD/lib/
export C_INCDIR=$HSRC/include
export C_COMPILER==$HHOSTBIN/nc
export LINKER=$HHOSTBIN/asm
export ASSEMBLER=$HHOSTBIN/asm
export GCCINCLUDE=/usr/include
export HOSTINCLUDE=$HSRC/hostinclude

export NEW_NCC=OLD_ARM

if [ -d LINUX_AMD64 ]; then
	cd LINUX_AMD64; make $*
else
       	make $*
fi

